# Generated by Django 5.1.1 on 2024-10-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='firstName', max_length=255)),
                ('last_name', models.CharField(db_column='lastName', max_length=255)),
                ('username', models.CharField(db_column='username', max_length=255, unique=True)),
                ('password', models.CharField(db_column='userPassword', max_length=128)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('phone_number', models.CharField(db_column='phoneNumber', max_length=9)),
                ('userrole', models.CharField(db_column='userRole', max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
