# Generated by Django 5.1.1 on 2024-10-20 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='firstName', max_length=255)),
                ('last_name', models.CharField(db_column='lastName', max_length=255)),
                ('username', models.CharField(db_column='username', max_length=255, unique=True)),
                ('password', models.CharField(db_column='userPassword', max_length=128)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('phone_number', models.CharField(db_column='phoneNumber', max_length=9)),
                ('userrole', models.CharField(db_column='userRole', max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(db_column='animalID', primary_key=True, serialize=False)),
                ('species', models.CharField(db_column='species', max_length=255)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('gender', models.SmallIntegerField(db_column='gender')),
                ('birth_date', models.DateField(blank=True, db_column='birthDate', null=True)),
                ('arrival_date', models.DateField(db_column='arrivalDate')),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('breed', models.CharField(db_column='breed', max_length=255)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('image_id', models.AutoField(db_column='photoID', primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='imagePath', upload_to='')),
                ('animal_id', models.ForeignKey(db_column='animalID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='project.animal')),
            ],
            options={
                'db_table': 'AnimalPhoto',
            },
        ),
    ]
