# Generated by Django 5.1.1 on 2024-10-24 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('record_id', models.AutoField(db_column='recordID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('detail', models.TextField(db_column='detail')),
                ('animal_id', models.ForeignKey(db_column='animalID', on_delete=django.db.models.deletion.CASCADE, related_name='med_records', to='project.animal')),
                ('veterinarian', models.ForeignKey(db_column='veterinarianID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HealthRecord',
            },
        ),
    ]
