# Generated by Django 5.1.1 on 2024-10-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('image_id', models.AutoField(db_column='photoID', primary_key=True, serialize=False)),
                ('animal_id', models.IntegerField(db_column='animalID')),
                ('image', models.ImageField(db_column='imagePath', upload_to='')),
            ],
            options={
                'db_table': 'AnimalPhoto',
            },
        ),
    ]
