# Generated by Django 5.1.1 on 2024-10-24 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_healthrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTask',
            fields=[
                ('task_id', models.AutoField(db_column='taskID', primary_key=True, serialize=False)),
                ('detail', models.TextField(db_column='detail')),
                ('animal_id', models.ForeignKey(db_column='animalID', on_delete=django.db.models.deletion.CASCADE, related_name='animal_tasks', to='project.animal')),
                ('veterinarian', models.ForeignKey(db_column='veterinarianID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
