# Generated by Django 5.1.1 on 2024-11-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_healthrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(db_column='reservationID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='start')),
                ('end_time', models.DateTimeField(db_column='end')),
                ('type', models.CharField(db_column='type', max_length=16)),
                ('animal', models.ForeignKey(db_column='animalID', on_delete=django.db.models.deletion.CASCADE, to='project.animal')),
                ('owner', models.ForeignKey(db_column='ownerID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('confirmation', models.CharField(db_column='confirmation', max_length=16)),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
    ]
