# Generated by Django 5.1.1 on 2024-10-26 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_reservation_checkup_walking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTask',
            fields=[
                ('task_id', models.AutoField(db_column='taskID', primary_key=True, serialize=False)),
                ('detail', models.TextField(db_column='detail')),
                ('is_done', models.BooleanField(db_column='isDone', default=False)),
                ('animal_id', models.ForeignKey(db_column='animalID', on_delete=django.db.models.deletion.CASCADE, related_name='animal_tasks', to='project.animal')),
                ('veterinarian', models.ForeignKey(db_column='veterinarianID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, db_column='reservationID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.reservation')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
