# Generated by Django 5.1.1 on 2024-11-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_create_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(db_column='ownerID', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(db_column='type', default=type, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.CharField(db_column='confirmation', max_length=16),
        ),
    ]
