# Generated by Django 5.1.1 on 2024-11-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_reservation_caregiver_reservation_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walking',
            name='volunteer_id',
        ),
        migrations.RemoveField(
            model_name='walking',
            name='walk_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservationID',
            new_name='reservation_id',
        ),
        migrations.DeleteModel(
            name='CheckUp',
        ),
        migrations.DeleteModel(
            name='Walking',
        ),
    ]
